# fly.toml app configuration file generated for todomvc-liveview on 2023-12-10T13:55:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todomvc-liveview"
primary_region = "cdg"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  # release_command = "/app/bin/migrate" # migration has been moved to application startup

[env]
  DATABASE_PATH = "/mnt/todomvc_volume/todomvc.db"
  PHX_HOST = "todomvc-liveview.fly.dev"
  PORT = "8080"
  POOL_SIZE = 100

[[mounts]]
  source = "todomvc_volume"
  destination = "/mnt/todomvc_volume"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
